#!/bin/sh

case "$1" in
    start)
        if [ ! -f /etc/pointercal ]; then
            if [ -f /etc/profile.d/tslib.sh ]; then
                source /etc/profile.d/tslib.sh
            fi
            echo "Running ts_calibrate..."
            /usr/bin/ts_calibrate
        fi
        ;;
    stop)
        echo "Stopping tslib"
        ;;
    *)
        echo "usage: $0 { start | stop }" >&2
        exit 1
        ;;
esac

exit 0
