#! /bin/sh
### BEGIN INIT INFO
# Provides:          NetworkManager
# Required-Start:    $remote_fs dbus hal
# Required-Stop:     $remote_fs dbus hal
# Should-Start:	     $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: network connection manager
# Description:       Daemon for automatically switching network
#                    connections to the best available connection.
### END INIT INFO

set -e

prefix=/usr
exec_prefix=/usr
sbindir=/usr/sbin
localstatedir=/var

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="network connection manager"
NAME="NetworkManager"

DAEMON=${sbindir}/$NAME

PIDDIR=${localstatedir}/run/NetworkManager
PIDFILE=$PIDDIR/$NAME.pid

USER=root

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#. /lib/lsb/init-functions

test -f /etc/default/NetworkManager && . /etc/default/NetworkManager

WIFI_MAC_ADDR="$(ifconfig mlan0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | tr ":" "-")"
echo MAC is $WIFI_MAC_ADDR

#
#	Function that starts the daemon/service.
#
d_start() {
	if [ ! -d $PIDDIR ]; then
		mkdir -p $PIDDIR
		chown $USER:$USER $PIDDIR
	fi

	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--oknodo --user $USER --exec $DAEMON -- $DAEMON_OPTS --pid-file $PIDFILE

	local eth_set="$(nmcli c | grep wired)"
	echo eth=$eth_set
	if [ -z "$eth_set" ];
	then
		nmcli c add type eth ifname eth0 con-name wired autoconnect yes
		nmcli c mod wired connection.autoconnect-priority  3
	fi

	local modem_set="$(nmcli c | grep modem)"
	echo modem=$modem_set
	if [ -z "$modem_set" ];
	then
		nmcli c add type gsm ifname ttyUSB3 con-name cellular_modem autoconnect yes apn internetg
		nmcli c mod cellular_modem connection.autoconnect-priority  1
	fi

	nmcli c delete Hostspot || true
	nmcli con add type wifi ifname mlan0 con-name Hostspot autoconnect no ssid Netbeat_$WIFI_MAC_ADDR
	nmcli con modify Hostspot 802-11-wireless.mode ap 802-11-wireless.band bg ipv4.method shared
	nmcli con modify Hostspot wifi-sec.key-mgmt wpa-psk
	nmcli con modify Hostspot wifi-sec.psk "password"
	nmcli con up Hostspot
}

#
#	Function that stops the daemon/service.
#
d_stop() {
	start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE \
		 --oknodo --user $USER --exec $DAEMON

}


case "$1" in
  start)
	echo "Starting $DESC" "$NAME"
	rm /dev/ttyUSB2 || true
	d_start
	;;
  stop)
	echo "Stopping $DESC" "$NAME"
	d_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC" "$NAME"
	d_stop
	sleep 1
	d_start
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0

